import type { DeepDive } from '../../../types/curriculum';

/** #10 · Sphere 1 · Effort Justification & Induced Compliance Dissonance */
export const deepDive: DeepDive = {
  readingTimeMinutes: 14,
  hook: 'You spend an hour on two tasks: half of it emptying and refilling a tray of spools, half of it turning wooden pegs a quarter-turn at a time. It is as boring as it sounds. Then the researcher asks a favour: the assistant who briefs the next participant has not shown up, would you mind telling her the task was interesting? He offers you a dollar. You do it. Afterwards someone asks how much you actually enjoyed the pegs. Leon Festinger and James Carlsmith ran this in 1959, and the participants paid one dollar reported liking the tedious task more than the participants paid twenty — a serious sum at the time. More money, less attitude change. The twenty-dollar group had a reason for saying something they did not believe. The one-dollar group had none, so their minds supplied one by quietly revising the belief. Nobody decided to do this.',
  sections: [
    {
      heading: 'Two engines, routinely confused',
      body: [
        'Festinger’s theory has two arms that get collapsed into one slogan, and they behave differently enough that collapsing them will cost you.',
        'Induced compliance is the peg-turning arm: you do something that conflicts with what you believe, without enough external reason to explain it away, and the belief moves to meet the behaviour. Effort justification is the other arm: you pay a real cost — time, money, pain, humiliation — to obtain something, and its value inflates to match. Aronson and Mills put women through an embarrassing initiation before admitting them to a deliberately dull discussion group. The severe-initiation group rated the group more favourably than the mild-initiation group.',
        'Both arms run on the same parameter, and it is the one everyone skips: insufficient external justification. If you were paid handsomely, ordered to comply, or given no choice, there is nothing to resolve — the behaviour is fully explained by circumstances and the belief stays put. Dissonance requires that the person feels they chose it freely, for reasons that were not good enough.',
      ],
    },
    {
      heading: 'Why the mind is built to do this',
      body: [
        'Start with the alternative. A mind that could comfortably hold “I gave three years to this” alongside “this was worthless” at full intensity would be paralysed, and would look profoundly unreliable to everyone around it. Consistency is not vanity; it is what makes a person predictable enough to be worth cooperating with.',
        'Then consider what upward revaluation buys. It is a commitment device. The hunter who abandons a three-day pursuit at the first setback starves; the founder who accurately prices their odds in year two quits. Attachment that grows with cost keeps long-horizon projects alive through the stretch where the evidence looks bad and the payoff has not arrived.',
        'The discomfort appears to be real rather than metaphorical. Vincent van Veen and colleagues scanned people during an induced-compliance task and found activity in the dorsal anterior cingulate and anterior insula — regions tied to conflict monitoring and aversive states — tracked how much attitudes subsequently shifted.',
        'So loyalty generated by cost is not a flaw in the individual. It is the system working. It becomes a flaw the moment an organisation lets the people who paid the cost decide whether the spending continues.',
      ],
    },
    {
      heading: 'The move: cost becomes evidence',
      body: [
        'The precise operation is a conversion. What you paid gets retroactively treated as evidence about the quality of what you paid for. This is not stupidity — it is the only available reading of a situation where cost is the one fact everyone can see and quality is the thing nobody can measure. If it were not good, why would a sensible person have paid that much?',
        'Gerard and Mathewson closed off the obvious alternatives by replacing the embarrassing readings with electric shocks. Same pattern: more severe initiation, more liking for the group. That rules out both the idea that the original result was about sexual arousal and the idea that participants were simply relieved when the unpleasantness ended.',
        'Michael Norton, Daniel Mochon and Dan Ariely gave the effect its consumer name and found its boundary. People who assembled IKEA boxes, folded origami and built with Lego valued their own output far above what others would pay. But the inflation required completion: participants stopped before finishing, or whose creation was destroyed, showed no attachment at all.',
        'That boundary is the most useful operational fact here. The bonding agent is not suffering. It is suffering that terminated in a finished thing you can point at. A brutal project that shipped creates fierce loyalty; a brutal project that was cancelled creates none.',
      ],
      example: {
        label: 'The crown jewel nobody uses',
        body: 'Three years and roughly fifteen million dollars into a custom internal CRM, adoption sits at forty percent and the support queue is full of workarounds. The two executives who sponsored it still describe it in board materials as a strategic asset. They are not lying and they are not stupid. They defended it publicly at three consecutive offsites, lost a respected engineering director over it, and worked through two Christmases. For the tool to be mediocre, all of that has to have been a mistake — theirs, in public, on the record.',
      },
    },
    {
      heading: 'Competence and seniority make it worse',
      body: [
        'The effect scales with what was paid, and senior people pay more: more hours, more political capital, more public defences on the record. Each is an increment of cost requiring justification, so the person with the most authority over whether a project continues is reliably the person with the largest incentive to value it highly.',
        'Ability makes it worse a second way. Elliot Aronson’s revision located the discomfort in threat to the self-concept rather than in logical inconsistency, and Claude Steele’s self-affirmation work points the same way: dissonance-driven attitude change shrinks when people can affirm their competence in an unrelated domain. High performers have more self-concept at stake, and build better arguments to protect it.',
        'Public commitment locks the whole thing. Every meeting where someone defended the decision raises the price of reversing it, because reversal now indicts not only the original choice but every subsequent defence of it.',
        'So “show them the numbers” is close to the worst available intervention. Evidence attacks the conclusion and the self-concept in the same instant, which is precisely the configuration that predicts defence rather than update. You are not arguing with a spreadsheet error. You are asking someone to file a very expensive report about themselves.',
      ],
    },
    {
      heading: 'The switches, in both directions',
      body: [
        'It switches on when effort is high, the choice felt free, the commitment was public, the person feels personally responsible, external justification was thin — and, per the IKEA boundary, the effort produced something finished. Remove free choice and the effect largely disappears; someone who was ordered to do it has an explanation that costs them nothing.',
        'It switches off in ways that are counterintuitive but usable. Ample external justification kills it, which is the direct implication of the one-dollar-versus-twenty-dollar result. Self-affirmation elsewhere kills it. And Mark Zanna and Joel Cooper showed that participants who could attribute their unpleasant arousal to a placebo pill showed no attitude change — the discomfort has to be attributed to the inconsistency for the inconsistency to get repaired.',
        'Translated into practice: do not attack the belief, lower the price of releasing it. Supply an external justification that is true and non-indicting, then affirm the person somewhere real and unrelated before you ask. Run the same machinery in reverse when you want commitment — which is exactly why manufactured hardship works, and why it is worth refusing on those grounds.',
      ],
      example: {
        label: 'The onboarding that defends itself',
        body: 'A firm keeps a notoriously punishing seven-stage interview process. Its most vocal defenders are the people who went through it, and their stated reason is that it identifies people who handle pressure. Ask the diagnostic question instead: does anyone who did not pay this cost also rate the process highly? If every advocate is a survivor and every sceptic an outsider, the process is valued for what it extracted, not for what it selects. Hard-won things are also valued by people who did not pay for them.',
      },
    },
    {
      heading: 'The honest limits',
      body: [
        'There is a serious competing account and it never went away. Daryl Bem’s self-perception theory argues no inner discomfort is needed: people infer their attitudes by observing their own behaviour and its circumstances, exactly as an outsider would. Bem reproduced the Festinger and Carlsmith pattern using observers who were merely told what happened and asked to predict the participant’s attitude. The standard truce, from Fazio, Zanna and Cooper, divides the territory by how discrepant the behaviour is. State the effect confidently; state the mechanism tentatively.',
        'The classics are also small. Festinger and Carlsmith ran roughly twenty men per condition; Aronson and Mills a comparable number of women. These are 1959 studies with 1959 statistical standards. The induced-compliance paradigm has been reproduced very widely over sixty years, and that, not the original samples, is why it deserves weight.',
        'One adjacent paradigm has a documented flaw. Keith Chen and Jane Risen showed the classic free-choice design — rate options, choose between two closely rated ones, re-rate — can produce apparent preference change as a statistical artefact, because choosing reveals a pre-existing preference the ratings missed. That targets free-choice designs, not induced compliance or effort justification, where the manipulation is assigned. Popular writing on dissonance leans on free-choice results constantly without flagging it.',
        'Finally, the mirror-image error. Costly things are frequently good, and effort is often a real signal rather than a distortion. Treating every strong commitment as delusion is its own bias and a fast way to destroy things worth keeping. The diagnostic is not how hard people fought — it is whether anyone who paid nothing also values the thing.',
      ],
    },
  ],
  spotIt: [
    {
      signal: 'The thing is defended by the story of what it cost rather than by what it does.',
      meaning: 'Cost has been converted into evidence of quality. Nobody has stated a benefit that could be measured.',
    },
    {
      signal: 'The set of defenders maps exactly onto the set of people who paid.',
      meaning: 'Valuation is tracking personal investment rather than performance. A perfect overlap is effort justification, not assessment.',
    },
    {
      signal: 'Nobody who joined in the last year likes it.',
      meaning: 'The newcomer test is failing. People who paid nothing have no reason to inflate the value and report something closer to the truth.',
    },
    {
      signal: 'Proposing a change is met as an insult to the team rather than as a proposal.',
      meaning: 'The object is load-bearing for someone’s account of their own past decisions. You are no longer discussing a tool.',
    },
    {
      signal: 'A gruelling process is justified by what it builds in people, by people who survived it.',
      meaning: 'Classic initiation dynamics. Severity is being read as purpose, and everyone defending it paid the toll.',
    },
    {
      signal: 'Spend keeps rising while the estimate of remaining work stays constant.',
      meaning: 'The commitment has stopped responding to information. Each increment of cost raises the price of admitting the estimate was wrong.',
    },
  ],
  playbook: [
    {
      move: 'Ask the from-scratch question.',
      how: 'Say: “Nobody is questioning the work that went into this. Different question — if we were choosing today, with no history, at this price, would we pick it?” It moves the decision from the past, which is defended, to the future, which is negotiable.',
      watchOut: 'Deployed on everything it becomes a tool for relitigating settled decisions forever. Reserve it for commitments large enough to justify the disruption.',
    },
    {
      move: 'Separate honouring the sacrifice from allocating the next dollar — and say both halves out loud.',
      how: 'Say: “The nights this team put in are real and I will not pretend otherwise. That is a separate question from where the next two million goes.” Naming the split explicitly is what stops the second half being heard as a verdict on the first.',
    },
    {
      move: 'Affirm before you ask.',
      how: 'Self-affirmation in an unrelated domain reduces dissonance-driven defence. Say something true and specific first: “Your team shipped the hardest integration in this company last year. That is not in question here.” Then raise the issue.',
      watchOut: 'A generic affirmation, or one obviously serving as preamble to a knife, lands as manipulation and costs more than opening cold.',
    },
    {
      move: 'Run the outsider test.',
      how: 'Say: “Find me three people who did not build this and do rate it highly.” Concrete, non-accusatory, and it separates genuine hard-won value from value that exists only inside the people who paid for it.',
    },
    {
      move: 'Supply an external justification that permits exit without self-indictment.',
      how: 'Say: “The market moved. Nobody was pricing this in 2022, and the decision was right on what we knew.” This is the one-dollar-versus-twenty-dollar lever run backwards: sufficient external reason removes the need to defend the belief.',
      watchOut: 'It has to be true. A fabricated excuse offered to someone who knows better reads as condescension and hardens the position you were trying to soften.',
    },
    {
      move: 'Refuse to manufacture the effect on your own people.',
      how: 'When someone defends a punishing process because it “builds resilience”, ask what it selects for that a humane version would not. Voluntary, meaningful, completed effort creates real commitment; engineered hardship creates the same commitment to something that did not earn it.',
    },
  ],
  commonMisreads: [
    {
      misread: 'This is just the sunk-cost fallacy.',
      correction: 'Related but different. Sunk cost is a decision error about future spending, fixed by changing the decision rule. Effort justification is a change in what the person actually values, which no decision rule reaches. Most troubled programmes have both running, and they need different interventions.',
    },
    {
      misread: 'Pay people well and they will be more committed to the work.',
      correction: 'For internalised belief the relationship runs the other way — that is the point of the one-dollar result. Ample reward supplies an explanation that is not belief. This concerns attitude change, not pay policy: underpaying people to manufacture devotion is unethical and, once noticed, self-destroying.',
    },
    {
      misread: 'Only credulous or junior people fall for it.',
      correction: 'The effect scales with cost paid and self-relevance, not with credulity. High performers invest more, commit more publicly, and construct better justifications. The most senior person in the room is usually the most exposed, not the least.',
    },
    {
      misread: 'If you show them the numbers, they will let go.',
      correction: 'Evidence attacks the conclusion and the self-concept simultaneously, which is the configuration that reliably produces defence rather than update. What moves people is lowering the exit price: an honest external justification plus affirmation somewhere unrelated. Data comes second.',
    },
    {
      misread: 'Anything people fought hard for is overvalued.',
      correction: 'The mirror-image error, and an expensive one. Hard-won things are frequently excellent and effort is often a genuine signal. The diagnostic is not intensity of attachment but whether people who paid nothing also value it, and whether you would choose it again at today’s price.',
    },
  ],
  evidence: [
    {
      source: 'Festinger & Carlsmith, “Cognitive Consequences of Forced Compliance” (1959)',
      finding: 'Participants paid one dollar to describe a tedious task as enjoyable later rated the task as more enjoyable than those paid twenty dollars or those in the control condition. Smaller external justification produced larger attitude change.',
      caveat: 'Roughly twenty male undergraduates per condition, under 1959 statistical standards. Its standing rests on sixty years of reproductions of the paradigm, not on the original sample.',
    },
    {
      source: 'Aronson & Mills, “The Effect of Severity of Initiation on Liking for a Group” (1959)',
      finding: 'Women who underwent an embarrassing initiation before joining a deliberately dull discussion group rated the group and the discussion more favourably than women given a mild initiation or none.',
      caveat: 'Small sample, and the sexual-embarrassment manipulation invited alternative readings — arousal, or relief at the end of the ordeal — which is why the shock replication matters more than the original.',
    },
    {
      source: 'Gerard & Mathewson, initiation replication (1966)',
      finding: 'Reproduced the severity-of-initiation effect using electric shocks in place of embarrassing material, removing both the sexual-arousal and the relief explanations. The severity endured, not its content, drove liking for the group.',
    },
    {
      source: 'Norton, Mochon & Ariely, “The IKEA Effect” (2012)',
      finding: 'People valued furniture, origami and Lego they had assembled themselves far above what others would pay. The effect required completion: participants stopped before finishing, or whose creation was destroyed, showed no inflated valuation.',
    },
    {
      source: 'Bem, self-perception theory (1967, 1972)',
      finding: 'Argues no internal discomfort is required — people infer their attitudes by observing their own behaviour and its circumstances. Bem reproduced the Festinger and Carlsmith pattern using outside observers who only read a description of the procedure.',
      caveat: 'A live competing account, not a footnote. The working settlement, from Fazio, Zanna and Cooper, assigns self-perception to attitude-congruent behaviour and dissonance to clearly discrepant behaviour. Assert the effect, not the mechanism.',
    },
    {
      source: 'Zanna & Cooper, misattribution study (1974)',
      finding: 'Participants who could attribute their unpleasant arousal to a placebo pill they believed might cause tension showed no attitude change, supporting the view that dissonance involves genuine aversive arousal that must be attributed to the inconsistency.',
      caveat: 'A small study, and the broader misattribution-of-arousal literature has had mixed replication results. Supporting evidence for the arousal account, not proof of it.',
    },
    {
      source: 'van Veen, Krug, Schooler & Carter, neuroimaging of induced compliance (2009)',
      finding: 'Activity in the dorsal anterior cingulate and anterior insula during a counter-attitudinal task predicted the size of the subsequent attitude change, linking the effect to conflict-monitoring and aversive-state circuitry.',
      caveat: 'Small fMRI sample and correlational. Inferring a specific psychological state from activation in these regions is a known weak point — read it as consistent with the arousal account, not as demonstrating it.',
    },
    {
      source: 'Chen & Risen, “How Choice Affects and Reflects Preferences” (2010)',
      finding: 'Showed that the classic free-choice paradigm can produce apparent preference change as a statistical artefact, because the act of choosing reveals a pre-existing preference the initial ratings failed to capture.',
      caveat: 'Applies to free-choice designs, not to induced compliance or effort justification, where the manipulation is assigned. Worth knowing because popular accounts lean on free-choice results without flagging it.',
    },
  ],
  takeaways: [
    'Cost gets converted into evidence of quality, because cost is visible and quality usually is not.',
    'The active ingredient is insufficient external justification. Ample reason, or no free choice, and the effect largely disappears.',
    'Completion is the boundary: unfinished or destroyed effort produces no attachment. Pain alone bonds nobody to anything.',
    'Seniority and competence increase exposure — more paid, more publicly defended, better arguments available for the defence.',
    'Evidence attacks the conclusion and the self-concept together, which predicts defence. Lower the exit price before presenting numbers.',
    'The clean diagnostic: does anyone who paid nothing also value this, and would we choose it again today at today’s price?',
  ],
};
