import type { DeepDive } from '../../../types/curriculum';

/** #12 · Sphere 2 · Preference Falsification & Pluralistic Ignorance */
export const deepDive: DeepDive = {
  readingTimeMinutes: 14,
  hook: 'In 1989 the Eastern Bloc collapsed, and almost nobody had predicted it — not the intelligence services, not the academic Sovietologists who had spent careers on the region, and not, by their own accounts, most of the people who came out onto the streets. The explanation is not that the regimes were secretly strong. It is that nobody, including the citizens themselves, could measure how many people privately wanted them gone, because every one of those people had spent decades saying the opposite in public. The opposition was enormous and invisible at the same time. Now transpose that to a Thursday afternoon. A director asks eleven people whether the plan makes sense. Eleven people nod. Six of them message each other afterwards.',
  sections: [
    {
      heading: 'Two different failures wearing one name',
      body: [
        'Popular writing runs these together, and the conflation costs you the intervention. They are separate mechanisms with separate fixes.',
        'Preference falsification is something you do. You know your own view perfectly well and you misrepresent it in public, because the reputational cost of stating it exceeds the satisfaction of saying what you think. Timur Kuran built the formal account: we each run a trade-off between expressive utility — the pleasure of saying the true thing — and reputational utility, which depends entirely on what we expect others to think of the position. It is deliberate, and the person doing it is not confused about anything.',
        'Pluralistic ignorance is something you believe. It is a misperception: you think most people hold a view that most people privately do not. You are not lying. You sampled the room from public behaviour and got the wrong answer, because public behaviour was not generated by private belief.',
        'The distinction matters because the two exist independently. You can have pluralistic ignorance with almost no lying — nobody said anything false, people simply never spoke, and silence got read as assent. And you can have universal falsification with zero ignorance: in a mature authoritarian system everyone applauds and everyone knows everyone is applauding under compulsion. Nobody is deceived and nobody moves, because the cost of being first to stop is still yours alone. Diagnose that room as a misperception problem and try to fix it with better information, and you will fail. It was never an information problem.',
      ],
    },
    {
      heading: 'Why lying about your preferences is correct arithmetic',
      body: [
        'The mistake is to treat the silent nodders as cowards. They are running the sum accurately. The first person to voice a dissent absorbs the entire cost of dissenting: the awkward pause, the suspicion of being difficult, the permanent association between their name and the objection, the small adjustment in how the most senior person in the room sees them. What they get in exchange is a marginal, uncertain effect on a decision that has visibly already converged. Silence is not weakness. It is a correct read of a bad trade.',
        'What makes the system fragile is that the cost is not constant. It falls steeply with each additional dissenter. The second objector is joining something rather than starting it; the fifth is stating the obvious. Kuran’s central point is the resulting non-linearity: a distribution of private views stable for years can invert in days once the threshold-crossing chain starts, and nobody could forecast the timing, because the private distribution was never observable. This is why regimes, orthodoxies and doomed corporate initiatives all look robust right up until they do not.',
        'The uncomfortable corollary is that the apparent stability of any consensus tells you nothing about its depth. Rooms that agree fast, on the record, in front of the boss, produce the observation you would expect whether the agreement is genuine or entirely hollow. The measurement is uninformative by construction.',
      ],
    },
    {
      heading: 'The move that does the damage: reading behaviour as belief',
      body: [
        'Falsification alone would be survivable. What converts it into a self-sustaining trap is one specific inferential error, committed by everyone in the room simultaneously.',
        'You know your own nod was strategic. You experienced the calculation — the flicker of hesitation, the decision not to spend capital on this one. You have full access to the gap between your face and your mind. You have no such access to anyone else’s, so you take their nod at face value. Their silence gets attributed to genuine agreement; yours gets attributed to circumstance. Everyone applies this asymmetry at the same moment, and you get eleven people each concluding they are the only sceptic.',
        'That conclusion then raises the price of speaking. Being one of many objectors is cheap; being the sole objector against a unanimous room is expensive, and now you believe that is what you would be. So you falsify harder, which strengthens the misperception for everyone else, which raises their cost, and the loop closes. Neither one caused the other first.',
        'There is a nastier turn documented by Willer, Kuwabara and Macy: people who privately reject a norm sometimes enforce it on others more aggressively than true believers do, because visible enforcement is the cheapest available proof of sincerity. The loudest advocate in the room can be the person with the deepest private doubts, defending against exactly the suspicion you would have of them. Enthusiasm is not evidence either.',
      ],
      example: {
        label: 'The board that voted yes twice',
        body: 'A CEO brings a $500M acquisition to the board. Each director has read the pack and each has the same worry about integration cost. The first two speakers make approving noises about strategic fit — because approving noises are the safe opening move, not because they are convinced. Every director after that is facing what looks like an emerging consensus, and revises their read of the room rather than their read of the deal. The vote is unanimous. That evening four separate phone calls happen, each discovering the other had doubts, each concluding the remaining directors were the believers. Nobody lied, and everyone who later says they had reservations will be telling the truth.',
      },
    },
    {
      heading: 'Seniority makes your information worse',
      body: [
        'The instinct is that experience inoculates you. It does the opposite, and the mechanism is structural rather than psychological. Preference falsification is a function of the cost of dissent, and that cost scales with the power of whoever is listening. The more senior you become, the more expensive it is for anyone to contradict you, so the more filtered your input — and the filtering is invisible, because what arrives is fluent, confident agreement that looks exactly like validation. Every promotion degrades your data quality while improving your apparent track record of being right in meetings. Those are the same phenomenon from different seats.',
        'It gets worse when you know the theory. Understanding groupthink does not immunise you, because what stops people speaking is not ignorance of the concept. Asch’s participants were not confused about which line was longer, and Asch was careful about this: most conforming responses came from people who saw the correct answer perfectly well and went along anyway. The failure was never perceptual. It was a decision about what to say, and knowing the name of the phenomenon changes nothing about the price of saying it.',
        'Your own falsification is also invisible to you in a way other people’s is not. Ask when you last held a real objection and let it go — not because you were persuaded, but because it was not the day for it, or the room had moved, or you had already spent your capital that week. Most people find an example in ten seconds. Now note that everyone else recorded your silence as agreement, and that you have no idea how many of theirs you recorded the same way.',
      ],
      example: {
        label: 'The Saudi labour experiment',
        body: 'Bursztyn, González and Yanagizawa-Drott surveyed young married men in Saudi Arabia and found a large majority privately supported women working outside the home — while most substantially underestimated how many other men agreed. The researchers then randomly told some participants the true distribution of local opinion. Men who received the correction became markedly more likely to sign their wives up for a job-matching service, and months later their wives were more likely to have actually applied and interviewed. Nothing about anyone’s own preference changed. Only their belief about everyone else did, and real labour-market behaviour moved as a result.',
      },
    },
    {
      heading: 'The switches that turn it on and off',
      body: [
        'Almost all the variance sits in a small number of structural conditions, and every one is yours if you are running the meeting.',
        'It intensifies when responses are public and attributable; when they are sequential rather than simultaneous, so later speakers see earlier ones; when the group appears unanimous; when the question implies a correct answer a competent person would already know; when the asker has power over the answerers; and when the decision looks already made, so dissent buys nothing while costing the same.',
        'It collapses on one variable more than any other: unanimity. Asch found that adding a single confederate who broke ranks cut conformity dramatically — and it worked even when that person gave a different wrong answer. The ally does not need to be right, or even to agree with you. They only need to demonstrate that disagreeing with the group is survivable. That is the cheapest intervention in this entire field, and it means one named, expected dissenter changes the arithmetic for everyone else in the room.',
        'The other reliable switches: private, simultaneous collection before any discussion; numbers instead of positions, because a confidence score of six is a dissent that costs almost nothing to voice; asking about the third person rather than the first, since people report an objection as somebody else’s far more readily than as their own; and the senior person speaking last, or not attending the first pass at all.',
      ],
    },
    {
      heading: 'The limits, including the one that will catch you',
      body: [
        'Sometimes the consensus is simply real. Silence is genuinely ambiguous — it means suppressed dissent, or agreement, or indifference, or that people have thought about it less than you have. Treating every quiet room as a suppressed one turns you into the person who cannot accept a decision, which is a fast way to lose the standing you need to break a real silence later.',
        'You also cannot infer the size of hidden opposition from the fact of silence. This is the error that makes the concept dangerous rather than useful. Kuran’s model explains why the private distribution is unobservable — and unobservable cuts both ways. You do not know that most of the room agrees with you either. Everyone who believes in preference falsification believes the silent majority secretly shares their view, and in any given room most of them are wrong. The theory tells you the measurement is broken. It does not hand you the answer.',
        'Nor is the timing forecastable. Cascades are genuinely unpredictable, which is precisely Kuran’s point about 1989: the same latent distribution can sit stable for years then invert in a week, and understanding the mechanism gives you no trigger date. Anyone selling a prediction of when an orthodoxy will break is selling something the theory says cannot be known.',
        'And be careful about scale. Some falsification is just manners. Not saying that a colleague’s slide template is ugly is not a governance failure. The concept earns its keep on decisions that are consequential, hard to reverse, and where the private objections are specific and technical. Applied to everything, it becomes a licence to treat ordinary social lubrication as institutional rot.',
      ],
    },
  ],
  spotIt: [
    {
      signal: 'Agreement in the room is total, and the corridor conversation afterwards is not.',
      meaning: 'The public and private distributions have separated. The meeting measured the cost of dissent, not the quality of the plan.',
    },
    {
      signal: 'The first two speakers set a tone and everyone after them elaborates rather than evaluates.',
      meaning: 'Sequential disclosure. Later speakers are updating on the room rather than the proposal, which is how a false consensus assembles itself.',
    },
    {
      signal: 'Objections arrive attributed to absent people — "the field team will hate this".',
      meaning: 'A real objection laundered through a third party. Owning it directly was judged too expensive, which tells you the price of dissent here.',
    },
    {
      signal: 'The most vocal defender of the decision is someone with no stake in it.',
      meaning: 'Possible false enforcement. Loud advocacy is the cheapest proof of sincerity available to a private doubter, so volume is not evidence of belief.',
    },
    {
      signal: 'Every question is about implementation and none about whether to do it at all.',
      meaning: 'The prior question has been quietly closed. People have concluded reopening it is unavailable, and are optimising inside a frame nobody endorsed aloud.',
    },
    {
      signal: 'You personally let an objection go and told yourself it was not the right moment.',
      meaning: 'That is you falsifying, in real time. Everyone else recorded your silence as agreement, and you are now part of why they will stay quiet too.',
    },
  ],
  playbook: [
    {
      move: 'Collect privately, reveal simultaneously.',
      how: '"Before anyone speaks: everyone write a number one to ten for how confident you are we ship on time, plus the single biggest reason it fails. Sixty seconds. Then we read every card out." Simultaneous private commitment removes sequential updating, which is where most of the damage happens.',
      watchOut: 'If anyone speaks before the cards are written, you have measured conformity instead. The order is non-negotiable.',
    },
    {
      move: 'Go last if you have power, and say why.',
      how: '"I am going to hold my view until the end, because if I go first you will all be reacting to me instead of to the problem." Saying the reason aloud is what makes it work — otherwise your silence reads as disapproval and people optimise against that instead.',
      watchOut: 'Only helps if your view genuinely stays hidden. Your reactions while others talk are read far more carefully than anything you eventually say.',
    },
    {
      move: 'Appoint the dissenter so nobody has to volunteer.',
      how: '"Priya, for the next ten minutes your job is to make the strongest case against this. Not because you disagree — because someone has to, and it should not cost anyone to be that person." Asch’s partner effect is the finding: breaking unanimity is what matters, not whether the dissenter is right.',
      watchOut: 'Rotate the role, and never assign it to the most junior person twice running, or you have created a job title for being difficult.',
    },
    {
      move: 'Ask about the third person, not the first.',
      how: '"What do you think the delivery team will say about this when we are not in the room?" People voice a private objection as somebody else’s reliably, and once it is in the air as a legitimate concern, owning it becomes cheap.',
      watchOut: 'Do not then demand they say whether they personally agree. That converts a free dissent back into an expensive one, and they will not do it again.',
    },
    {
      move: 'Convert positions into numbers.',
      how: 'Never ask "does everyone agree." Ask "how confident are you, one to ten, that this hits the March date." A six is a full dissent that costs nothing to state, and it gives you a distribution instead of a nod.',
      watchOut: 'Follow up on low scores privately and gently. If people learn a six triggers public interrogation, everyone reports eights forever.',
    },
    {
      move: 'Pay the cost yourself, first and visibly.',
      how: '"I will go first because it is cheapest for me. I think there is maybe a forty percent chance this lands, and here is what would change my mind." Then, when someone else objects, thank them by name in front of the group and change something because of it.',
      watchOut: 'This is the only move that can permanently make things worse. Invite the objection then freeze out or quietly overrule the first person who takes you up on it, and you have proved the cost is real — the room will be more rigid than before you started.',
    },
  ],
  commonMisreads: [
    {
      misread: 'Preference falsification and pluralistic ignorance are two names for the same thing.',
      correction: 'One is a misrepresentation you perform knowing your own view; the other is a misperception you hold about everyone else. They compound, but the fixes differ: falsification responds to lowering the cost of speaking, ignorance responds to revealing the actual distribution.',
    },
    {
      misread: 'If the room is silent, most of them secretly agree with me.',
      correction: 'The theory says the private distribution is unobservable. That applies to your side too. Everyone who knows about preference falsification assumes the hidden majority is theirs, and most of them are wrong.',
    },
    {
      misread: 'Asch showed that people cannot trust their own eyes under group pressure.',
      correction: 'Asch was explicit that most conforming responses came from people who saw the correct answer and said something else anyway. It is a finding about the price of speaking, not about perception — which is why intelligence and expertise do not protect against it.',
    },
    {
      misread: 'The Abilene Paradox is evidence for this.',
      correction: 'Harvey’s Abilene story is a management essay built on a family anecdote. Excellent teaching device, not data. The evidentiary weight sits with Asch, Kuran’s historical analysis, and field experiments like the Saudi labour study.',
    },
    {
      misread: 'Enough psychological safety and this goes away.',
      correction: 'Safety lowers the cost of dissent but never to zero, and the mechanism runs on the cost being non-zero. Structural moves — private simultaneous collection, an appointed dissenter, numbers instead of positions — work even in rooms with mediocre safety, which is most rooms.',
    },
  ],
  evidence: [
    {
      source: 'Kuran, Private Truths, Public Lies (1995) and "Now Out of Never" (1991)',
      finding: 'Models public opinion as a trade-off between the satisfaction of saying what you think and the reputational cost of saying it. Because the cost of dissent falls with each additional dissenter, stable-looking orthodoxies can invert suddenly — and the timing is unforecastable, since the private distribution was never observable. Applied to explain why the 1989 collapses surprised participants and analysts alike.',
    },
    {
      source: 'Asch line-judgement studies (1951–1956)',
      finding: 'With a unanimous majority giving an obviously wrong answer, participants conformed on roughly a third of critical trials and about three-quarters conformed at least once. Control-condition error rates were under one percent. Asch reported that most conformers knew the right answer and went along regardless.',
    },
    {
      source: 'Asch, the partner and unanimity variations',
      finding: 'Introducing a single confederate who broke with the majority cut conformity sharply — and it worked even when that dissenter gave a different wrong answer. What matters is the break in unanimity, not the correctness of the ally.',
    },
    {
      source: 'Bond & Smith, meta-analysis of Asch-paradigm studies (1996)',
      finding: 'Pooled 133 studies across 17 countries. Conformity is robust but far from constant: it declined in the United States over the decades following the original work and was substantially larger in more collectivist cultures.',
      caveat: 'The important qualifier on any confident number. Effect size is strongly moderated by era, culture, group size and task ambiguity, so treat the classic one-third figure as one condition, not a constant of human nature.',
    },
    {
      source: 'Bursztyn, González & Yanagizawa-Drott, "Misperceived Social Norms" (2020)',
      finding: 'A large majority of young married Saudi men privately supported women working outside the home while most underestimated support among other men. Randomly correcting that misperception increased sign-ups for a wives’ job-matching service, and months later the wives of treated men were more likely to have applied and interviewed for jobs.',
    },
    {
      source: 'Willer, Kuwabara & Macy, "The False Enforcement of Unpopular Norms" (2009)',
      finding: 'People who privately reject a norm can enforce it on others more aggressively than genuine believers, because visible enforcement is the cheapest way to prove sincerity. Loud public advocacy is therefore not evidence of private conviction.',
    },
    {
      source: 'Prentice & Miller, campus alcohol norms (1993)',
      finding: 'A clean demonstration of pluralistic ignorance: students were individually more uncomfortable with campus drinking norms than they believed the average student to be, and adjusted their behaviour toward a norm almost nobody held.',
      caveat: 'The descriptive finding is solid; the intervention built on it is not. Social-norms marketing campaigns derived from this work have produced inconsistent field results, including a large multi-campus study that found no reduction in drinking.',
    },
    {
      source: 'Noelle-Neumann, the spiral of silence (1974, 1984)',
      finding: 'Proposes that people who perceive their view to be in the minority become progressively less willing to express it, accelerating the apparent dominance of the majority position.',
      caveat: 'Weakly supported relative to its fame. Meta-analytic work has found the link between perceived opinion climate and willingness to speak out to be positive but small. Use it as framing; the load-bearing evidence is Asch, Kuran and the field experiments.',
    },
  ],
  takeaways: [
    'Falsification is a lie you tell about yourself; pluralistic ignorance is a mistake you make about everyone else. They feed each other and need different fixes.',
    'You know your own nod was strategic and assume everyone else’s was sincere. That asymmetry, applied simultaneously by everyone, manufactures the false consensus.',
    'The first dissenter pays the whole bill and the fifth pays nothing, which is why consensus can look solid for years and invert in a week.',
    'Seniority does not protect you — it degrades your input, because the cost of contradicting you rises with every promotion and the filtering is invisible from your seat.',
    'Break unanimity rather than winning the argument: one appointed dissenter changes the price for everyone, even when that dissenter is wrong.',
    'The theory says the private distribution is unmeasurable. That includes yours — do not assume the silent majority is on your side.',
  ],
};
