/**
 * Concepts that have a written deep dive.
 *
 * Kept as a plain list so the UI can decide whether to offer a read without first
 * downloading a large code-split chunk.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 */
export const CONCEPTS_WITH_DEEP_DIVE: ReadonlySet<string> = new Set([
  'affect-heuristic-somatic-markers',
  'bayesian-updating-base-rate-neglect',
  'costly-signaling-status-typologies',
  'counter-signaling-theory',
  'decision-fatigue-depletion-traps',
  'diffusion-of-responsibility-bystander-paradigm',
  'dual-process-miserliness',
  'effort-justification-dissonance',
  'emotional-contagion-autonomic-mirroring',
  'epistemic-arrogance-overprecision',
  'fundamental-attribution-error',
  'identity-protective-cognition',
  'illusion-of-explanatory-depth',
  'informational-cascades-social-proof',
  'minimal-group-paradigm-in-group-favoritism',
  'moral-foundations-sacred-values',
  'naive-realism-bias-blind-spot',
  'preference-falsification-pluralistic-ignorance',
  'press-secretary-confabulation',
  'prospect-theory-framing-asymmetry',
  'psychological-reactance-autonomy-defense',
  'signaling-asymmetry-adverse-selection',
  'strategic-reciprocity-concession-framing',
  'sunk-cost-fallacy-escalation-of-commitment',
  'winners-curse-ego-escalation',
]);
