/**
 * Concepts that have a written deep dive.
 *
 * Kept as a plain list so the UI can decide whether to offer a read without first
 * downloading a large code-split chunk.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 */
export const CONCEPTS_WITH_DEEP_DIVE: ReadonlySet<string> = new Set([
  'affect-heuristic-somatic-markers',
  'affect-labeling-de-escalation',
  'batna-power-dependence-relations',
  'bayesian-updating-base-rate-neglect',
  'choice-architecture-default-mechanics',
  'cobra-effect-perverse-feedback-loops',
  'commitment-devices-strategic-inflexibility',
  'costly-signaling-status-typologies',
  'counter-signaling-theory',
  'decision-fatigue-depletion-traps',
  'diffusion-of-responsibility-bystander-paradigm',
  'dopaminergic-prediction-error-variable-schedules',
  'dual-process-miserliness',
  'effort-justification-dissonance',
  'emotional-contagion-autonomic-mirroring',
  'endowment-effect-divestiture-aversion',
  'epistemic-arrogance-overprecision',
  'extrinsic-incentive-crowding-out',
  'fixed-pie-perception-integrative-bargaining',
  'focal-points-anchoring-gravity-wells',
  'fundamental-attribution-error',
  'goodharts-campbells-laws',
  'hyperbolic-discounting-present-bias',
  'identity-protective-cognition',
  'illusion-of-explanatory-depth',
  'informational-cascades-social-proof',
  'mental-accounting-non-fungibility',
  'minimal-group-paradigm-in-group-favoritism',
  'moral-foundations-sacred-values',
  'naive-realism-bias-blind-spot',
  'preference-falsification-pluralistic-ignorance',
  'press-secretary-confabulation',
  'prospect-theory-framing-asymmetry',
  'psychological-reactance-autonomy-defense',
  'signaling-asymmetry-adverse-selection',
  'strategic-ambiguity-off-record-speech',
  'strategic-reciprocity-concession-framing',
  'sunk-cost-fallacy-escalation-of-commitment',
  'tit-for-tat-retaliatory-discipline',
  'winners-curse-ego-escalation',
]);
