/**
 * Concepts that have a written deep dive.
 *
 * Kept as a plain list so the UI can decide whether to offer a read without first
 * downloading a large code-split chunk.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 */
export const CONCEPTS_WITH_DEEP_DIVE: ReadonlySet<string> = new Set([
  'dual-process-miserliness',
]);
