import type { DeepDive } from '../../types/curriculum';
import { deepDive as costlySignalingStatusTypologies } from './concepts/costly-signaling-status-typologies';
import { deepDive as counterSignalingTheory } from './concepts/counter-signaling-theory';
import { deepDive as diffusionOfResponsibilityBystanderParadigm } from './concepts/diffusion-of-responsibility-bystander-paradigm';
import { deepDive as emotionalContagionAutonomicMirroring } from './concepts/emotional-contagion-autonomic-mirroring';
import { deepDive as informationalCascadesSocialProof } from './concepts/informational-cascades-social-proof';
import { deepDive as minimalGroupParadigmInGroupFavoritism } from './concepts/minimal-group-paradigm-in-group-favoritism';
import { deepDive as moralFoundationsSacredValues } from './concepts/moral-foundations-sacred-values';
import { deepDive as preferenceFalsificationPluralisticIgnorance } from './concepts/preference-falsification-pluralistic-ignorance';
import { deepDive as psychologicalReactanceAutonomyDefense } from './concepts/psychological-reactance-autonomy-defense';
import { deepDive as strategicReciprocityConcessionFraming } from './concepts/strategic-reciprocity-concession-framing';

/**
 * Long-form deep dives for Sphere 2, keyed by concept id.
 * Code-split — loaded on demand by `src/data/deepdives/index.ts`.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 * Add a file under `./concepts/` and re-run the script instead.
 */
export const SPHERE_2_DEEP_DIVES: Record<string, DeepDive> = {
  'costly-signaling-status-typologies': costlySignalingStatusTypologies,
  'counter-signaling-theory': counterSignalingTheory,
  'diffusion-of-responsibility-bystander-paradigm': diffusionOfResponsibilityBystanderParadigm,
  'emotional-contagion-autonomic-mirroring': emotionalContagionAutonomicMirroring,
  'informational-cascades-social-proof': informationalCascadesSocialProof,
  'minimal-group-paradigm-in-group-favoritism': minimalGroupParadigmInGroupFavoritism,
  'moral-foundations-sacred-values': moralFoundationsSacredValues,
  'preference-falsification-pluralistic-ignorance': preferenceFalsificationPluralisticIgnorance,
  'psychological-reactance-autonomy-defense': psychologicalReactanceAutonomyDefense,
  'strategic-reciprocity-concession-framing': strategicReciprocityConcessionFraming,
};
