import type { DeepDive } from '../../types/curriculum';

/**
 * Long-form deep dives for Sphere 4, keyed by concept id.
 * Code-split — loaded on demand by `src/data/deepdives/index.ts`.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 * Add a file under `./concepts/` and re-run the script instead.
 */
export const SPHERE_4_DEEP_DIVES: Record<string, DeepDive> = {};
