import type { DeepDive } from '../../types/curriculum';
import { deepDive as dualProcessMiserliness } from './concepts/dual-process-miserliness';

/**
 * Long-form deep dives for Sphere 1, keyed by concept id.
 * Code-split — loaded on demand by `src/data/deepdives/index.ts`.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 * Add a file under `./concepts/` and re-run the script instead.
 */
export const SPHERE_1_DEEP_DIVES: Record<string, DeepDive> = {
  'dual-process-miserliness': dualProcessMiserliness,
};
