import type { DeepDive } from '../../types/curriculum';
import { deepDive as affectLabelingDeEscalation } from './concepts/affect-labeling-de-escalation';
import { deepDive as batnaPowerDependenceRelations } from './concepts/batna-power-dependence-relations';
import { deepDive as commitmentDevicesStrategicInflexibility } from './concepts/commitment-devices-strategic-inflexibility';
import { deepDive as fixedPiePerceptionIntegrativeBargaining } from './concepts/fixed-pie-perception-integrative-bargaining';
import { deepDive as focalPointsAnchoringGravityWells } from './concepts/focal-points-anchoring-gravity-wells';
import { deepDive as prospectTheoryFramingAsymmetry } from './concepts/prospect-theory-framing-asymmetry';
import { deepDive as signalingAsymmetryAdverseSelection } from './concepts/signaling-asymmetry-adverse-selection';
import { deepDive as strategicAmbiguityOffRecordSpeech } from './concepts/strategic-ambiguity-off-record-speech';
import { deepDive as titForTatRetaliatoryDiscipline } from './concepts/tit-for-tat-retaliatory-discipline';
import { deepDive as winnersCurseEgoEscalation } from './concepts/winners-curse-ego-escalation';

/**
 * Long-form deep dives for Sphere 3, keyed by concept id.
 * Code-split — loaded on demand by `src/data/deepdives/index.ts`.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 * Add a file under `./concepts/` and re-run the script instead.
 */
export const SPHERE_3_DEEP_DIVES: Record<string, DeepDive> = {
  'affect-labeling-de-escalation': affectLabelingDeEscalation,
  'batna-power-dependence-relations': batnaPowerDependenceRelations,
  'commitment-devices-strategic-inflexibility': commitmentDevicesStrategicInflexibility,
  'fixed-pie-perception-integrative-bargaining': fixedPiePerceptionIntegrativeBargaining,
  'focal-points-anchoring-gravity-wells': focalPointsAnchoringGravityWells,
  'prospect-theory-framing-asymmetry': prospectTheoryFramingAsymmetry,
  'signaling-asymmetry-adverse-selection': signalingAsymmetryAdverseSelection,
  'strategic-ambiguity-off-record-speech': strategicAmbiguityOffRecordSpeech,
  'tit-for-tat-retaliatory-discipline': titForTatRetaliatoryDiscipline,
  'winners-curse-ego-escalation': winnersCurseEgoEscalation,
};
