import type { DeepDive } from '../../types/curriculum';
import { deepDive as prospectTheoryFramingAsymmetry } from './concepts/prospect-theory-framing-asymmetry';
import { deepDive as signalingAsymmetryAdverseSelection } from './concepts/signaling-asymmetry-adverse-selection';
import { deepDive as winnersCurseEgoEscalation } from './concepts/winners-curse-ego-escalation';

/**
 * Long-form deep dives for Sphere 3, keyed by concept id.
 * Code-split — loaded on demand by `src/data/deepdives/index.ts`.
 *
 * GENERATED by `scripts/sync-deepdives.mjs` — do not edit by hand.
 * Add a file under `./concepts/` and re-run the script instead.
 */
export const SPHERE_3_DEEP_DIVES: Record<string, DeepDive> = {
  'prospect-theory-framing-asymmetry': prospectTheoryFramingAsymmetry,
  'signaling-asymmetry-adverse-selection': signalingAsymmetryAdverseSelection,
  'winners-curse-ego-escalation': winnersCurseEgoEscalation,
};
